avoid long lines

diff --git a/.github/workflows/microk8s-func-test.yaml b/.github/workflows/microk8s-func-test.yaml
--- a/.github/workflows/microk8s-func-test.yaml
+++ b/.github/workflows/microk8s-func-test.yaml
@@ -56,7 +56,10 @@ jobs:
     - name: Check for errors in juju status
       run: |  
         sudo juju status 2>&1 | tee tmp/juju-status-metallb.txt
-        if [[ $(juju status | grep 'error\|blocked') ]]; then exit 1; else echo "No errors or blocked status detected."; fi
+        if [[ $(juju status | grep 'error\|blocked') ]];
+        then exit 1;
+        else echo "No errors or blocked status detected.";
+        fi
 
     - name: Check pods status
       run: |
@@ -72,7 +75,10 @@ jobs:
 
     - name: Curl service on microbot external ip
       run: |
-         if curl --fail --connect-timeout 10 `kubectl get service/microbot-lb --no-headers| awk '{print$4}'`; then echo "curl successfull"; else exit 1; fi      
+         if curl --fail --connect-timeout 10 `kubectl get service/microbot-lb \
+         --no-headers | awk '{print$4}'`; then echo "curl successfull";
+         else exit 1;
+         fi      
 
     - name: Upload Artifacts
       if: ${{ always() }}
