add gate check for juju status on error or blocked

diff --git a/.github/workflows/microk8s-func-test.yaml b/.github/workflows/microk8s-func-test.yaml
--- a/.github/workflows/microk8s-func-test.yaml
+++ b/.github/workflows/microk8s-func-test.yaml
@@ -52,7 +52,10 @@ jobs:
     - name: Wait for stable environment
       run: |
         sudo /snap/bin/juju-wait
+
+    - name: Check if no error in juju status
         sudo juju status 2>&1 | tee tmp/juju-status-metallb.txt
+        if [[ $(juju status | grep 'error\|blocked') ]]; then exit 1; else echo "No errors or blocked status detected."; fi
 
     - name: Check pods status
       run: |
@@ -68,7 +71,7 @@ jobs:
 
     - name: Curl service
       run: |
-         if curl --fail`kubectl get service/microbot-lb --no-headers| awk '{print$4}'`; then "curl succesfull"; else exit 1; fi      
+         if curl --fail `kubectl get service/microbot-lb --no-headers| awk '{print$4}'`; then "curl successfull"; else exit 1; fi      
 
     - name: Upload Artifacts
       if: ${{ always() }}
