add func test with rbac

diff --git a/.github/workflows/rbac-metallb-workflow.yaml b/.github/workflows/rbac-metallb-workflow.yaml
--- a/.github/workflows/rbac-metallb-workflow.yaml
+++ b/.github/workflows/rbac-metallb-workflow.yaml
@@ -1,75 +1,13 @@
 name: Test Suite for MetalLB
 
 on:
-  - pull_request_target
+  - pull_request
 
 jobs:
-  lint:
-    name: Check PEP8 formatting
-    runs-on: ubuntu-latest
-    steps:
-    - name: Check out code
-      uses: actions/checkout@v2
-
-    - name: Run Python code quality and lint action
-      uses: ricardochaves/python-lint@v1.3.0
-      with:
-        python-root-list: "charms"
-        use-flake8: true
-        use-pylint: false
-        use-pycodestyle: false
-        use-black: false
-        use-mypy: false
-        use-isort: false
-        extra-flake8-options: "--max-line-length=88 --max-complexity=10"
-
-  unit-test-metallb-controller:
-    name: Unit tests for charm metallb-controller
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python: [3.7, 3.8]
-    steps:
-    - name: Check out code
-      uses: actions/checkout@v2
-    - name: Setup Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python }}
-    - name: Install dependencies
-      run: |
-        pip install tox
-    - name: Run unit tests with tox
-      run: |
-        cd charms/metallb-controller
-        tox -e unit
-  
-  unit-test-metallb-speaker:
-    name: Unit tests for charm metallb-speaker
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python: [3.7, 3.8]
-    steps:
-    - name: Check out code
-      uses: actions/checkout@v2
-    - name: Setup Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python }}
-    - name: Install dependencies
-      run: |
-        pip install tox
-    - name: Run unit tests with tox
-      run: |
-        cd charms/metallb-speaker
-        tox -e unit
-
   func-test-metallb:
     runs-on: ubuntu-latest
-    name: Functional test MetalLB
+    name: Functional test with RBAC enabled
     timeout-minutes: 10
-    needs: [lint, unit-test-metallb-controller, unit-test-metallb-speaker]
     steps:
     - name: Check out code
       uses: actions/checkout@v2
@@ -92,14 +30,14 @@ jobs:
       uses: balchua/microk8s-actions@v0.1.2
       with:
         channel: '1.18/stable'
-        rbac: 'false'
+        rbac: 'true'
         dns: 'true'
         storage: 'true'
 
     - name: Bootstrap MicroK8s with Juju
       run: |
         sudo juju bootstrap microk8s microk8s
-
+    
     - name: Deploy MetalLB
       run: |
         sudo juju add-model metallb-system
@@ -107,6 +45,25 @@ jobs:
         sudo juju deploy ./metallb-speaker.charm --resource metallb-speaker-image='metallb/speaker:v0.9.3'
         sudo juju config metallb-controller iprange="10.1.240.240-10.1.240.241"
     
+    - name: Wait for stable environment
+      run: |
+        sudo /snap/bin/juju-wait
+
+    - name: Confirm failure without RBAC rules
+        sudo juju status 2>&1 | tee tmp/juju-status-metallb.txt
+        if [[ $(juju status | grep 'error\|blocked') ]];
+        then echo "Deployment failed as expected.";
+        else exit 1;
+        fi
+
+    - name: Apply RBAC rules for operator pods
+      run: sudo microk8s.kubectl apply -f docs/rbac-permissions-controller.yaml
+
+    - name: Resolve errored units
+      run: |
+        sudo juju resolve metallb-controller/0
+        sudo juju resolve metallb-speaker/0
+
     - name: Wait for stable environment
       run: |
         sudo /snap/bin/juju-wait
